name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    # setup Docker buld action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: ./ubuntu/24.04
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: |
          makzin/apachephp:latest
          makzin/apachephp:ubuntu24.04
